/*
REM ***************************************************************************************
PROMPT Nombre del Script: DTIYC_BROKER_ORACLE_20181010_V1.sql
PROMPT Proyecto: Broker Oracle
PROMPT RBVM 10 de Octubre del 2018
PROMPT Descripcion: Se crean alter en tablas cuotas
REM ***************************************************************************************
*/

ALTER TABLE NOMINA.PRN_TEACHER_PROFILE
  ADD ID_DOCENTE VARCHAR2(250);
ALTER TABLE NOMINA.PRN_TEACHER_PROFILE
  ADD PRIMER_NOMBRE VARCHAR2(50);
ALTER TABLE NOMINA.PRN_TEACHER_PROFILE
  ADD APELLIDOS VARCHAR2(50);
ALTER TABLE NOMINA.PRN_TEACHER_PROFILE
  ADD SEGUNDO_NOMBRE VARCHAR2(50);
ALTER TABLE NOMINA.PRN_TEACHER_PROFILE
  ADD PIDM NUMBER;
ALTER TABLE NOMINA.CUOTA
  ADD DIVISION VARCHAR2(100);

ALTER TABLE NOMINA.CUOTA
  ADD CONSTRAINT ID_DOCENTE_FK
      FOREIGN KEY (ID_DOCENTE)
      REFERENCES NOMINA.PRN_TEACHER_PROFILE(ID);

ALTER TABLE NOMINA.CUOTA DROP COLUMN FECHA_INGRESO;

ALTER TABLE NOMINA.CUOTA
  ADD FECHA_INGRESO DATE;